name: myproject library CI

on: [push]

jobs:

    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-18.04, ubuntu-16.04, windows-2019, windows-2016, macOS-10.14]
        steps:
            - uses: actions/checkout@v1
            - name: prepare
              run: pip install --user conan cmake
                   mkdir build
            - name: configure
              run: cmake ..
              working-directory: build
            - name: build
              run: cmake --build .
              working-directory: build

    #sanitized-build:

    #static-analyzed-build:
